#pragma once
#ifndef ENUMS_H
#define ENUMS_H


#ifdef __cplusplus
namespace GW2 {
#endif

	enum WeaponTypes {
		WEP_TYPE_SWORD,
		WEP_TYPE_HAMMER,
		WEP_TYPE_LONGBOW,
		WEP_TYPE_SHORTBOW,
		WEP_TYPE_AXE,
		WEP_TYPE_DAGGER,
		WEP_TYPE_GREATSWORD,
		WEP_TYPE_MACE,
		WEP_TYPE_PISTOL,
		WEP_TYPE_UNKNOWN,
		WEP_TYPE_RIFLE,
		WEP_TYPE_SCEPTER,
		WEP_TYPE_STAFF,
		WEP_TYPE_FOCUS,
		WEP_TYPE_TORCH,
		WEP_TYPE_WARHORN,
		WEP_TYPE_SHIELD,
		WEP_TYPE_NOEQUIP,
		WEP_TYPE_END
	};

	enum ClassTypes {
		CLASS_TYPE_CHAR,
		CLASS_TYPE_AGENT,
		CLASS_TYPE_WMAGENT,
		CLASS_TYPE_PLAYER,
		CLASS_TYPE_EQITEM,
		CLASS_TYPE_ITEM,
		CLASS_TYPE_SKILL,
		CLASS_TYPE_SPEC,
		CLASS_TYPE_TRAIT,
		CLASS_TYPE_BUFF,
		CLASS_TYPE_STAT,
		CLASS_TYPE_SKIN,
		CLASS_TYPE_UPGRADE,
		CLASS_TYPE_ITEMTYPE,
		CLASS_TYPE_SPECIESDEF,
		CLASS_TYPE_SPECIESID,
		CLASS_TYPE_SKILLID,
		CLASS_TYPE_END,
	};

	enum CharacterFlags {
		CHAR_FLAG_IN_COMBAT = 0x20,
		CHAR_FLAG_WEAP_DRAWN = 0x40
	};

	enum Profession {
		PROFESSION_NONE,
		PROFESSION_GUARDIAN,
		PROFESSION_WARRIOR,
		PROFESSION_ENGINEER,
		PROFESSION_RANGER,
		PROFESSION_THIEF,
		PROFESSION_ELEMENTALIST,
		PROFESSION_MESMER,
		PROFESSION_NECROMANCER,
		PROFESSION_REVENANT,
		PROFESSION_END
	};

	enum Race {
		RACE_ASURA,
		RACE_CHARR,
		RACE_HUMAN,
		RACE_NORN,
		RACE_SYLVARI,
		RACE_NONE
	};

	enum Attitude {
		ATTITUDE_FRIENDLY,
		ATTITUDE_HOSTILE,
		ATTITUDE_INDIFFERENT,
		ATTITUDE_NEUTRAL
	};

	enum AgentCategory {
		AGENT_CATEGORY_CHAR,
		AGENT_CATEGORY_DYNAMIC,
		AGENT_CATEGORY_KEYFRAMED
	};

	enum AgentType {
		AGENT_TYPE_CHAR = 0,
		AGENT_TYPE_GADGET = 10,
		AGENT_TYPE_GADGET_ATTACK_TARGET = 11,
		AGENT_TYPE_ITEM = 15
	};

	enum BreakbarState {
		BREAKBAR_STATE_READY,
		BREAKBAR_STATE_RECOVER,
		BREAKBAR_STATE_IMMUNE,
		BREAKBAR_STATE_NONE
	};

	enum UiIntefaceSize {
		UI_IF_SMALL,
		UI_IF_NORMAL,
		UI_IF_LARGE,
		UI_IF_LARGER
	};

	enum CombatLogType {
		CL_CONDI_DMG_IN,
		CL_CRIT_DMG_IN,
		CL_GLANCE_DMG_IN,
		CL_HEAL_IN,
		CL_PHYS_DMG_IN,
		CL_UNKNOWN_5,
		CL_UNKNOWN_6,
		CL_CONDI_DMG_OUT,
		CL_CRIT_DMG_OUT,
		CL_GLANCE_DMG_OUT,
		CL_HEAL_OUT,
		CL_PHYS_DMG_OUT,
		CL_UNKNOWN_12,
		CL_UNKNOWN_13
	};

	enum CombatLogResult {
		CBT_RESULT_BLOCK = 0,
		CBT_RESULT_EVADE = 5,
		CBT_RESULT_NORMAL = 7,
		CBT_RESULT_INTERRUPT = 8,
		CBT_RESULT_ABSORB = 9,
		CBT_RESULT_MISS = 12,
		CBT_RESULT_OBSTRUCTED = 19,
		CBT_RESULT_OUTOFRANGE = 20,
	};

	enum ProfessionStance {
		STANCE_NONE,
		STANCE_ELE_FIRE,
		STANCE_ELE_WATER,
		STANCE_ELE_AIR,
		STANCE_ELE_EARTH,
		STANCE_UNKNOWN1,
		STANCE_NECRO_SHROUD,
		STANCE_WAR_ADREN1,
		STANCE_WAR_ADREN2,
		STANCE_WAR_ADREN3,
		STANCE_RANGER_DRUID,
		STANCE_RANGER_ASTRAL,
		STANCE_UNKNOWN2,
		STANCE_REV_DRAGON,
		STANCE_REV_ASSASSIN,
		STANCE_REV_DWARF,
		STANCE_REV_DEMON,
		STANCE_UNKNOWN3,
		STANCE_REV_CENTAUR
	};

	enum SpecSlot {
		SPEC_SLOT_1,
		SPEC_SLOT_2,
		SPEC_SLOT_3,
		SPEC_SLOT_END
	};

	enum TraitSlot {
		TRAIT_SLOT_1,
		TRAIT_SLOT_2,
		TRAIT_SLOT_3,
		TRAIT_SLOT_END
	};

	enum Specialization {
		SPEC_NONE,
		SPEC_MES_DEULING,
		SPEC_NECRO_DEATH_MAGIC,
		SPEC_REV_INVOCATION,
		SPEC_WAR_STRENGTH,
		SPEC_RANGER_DRUID,
		SPEC_ENGI_EXPLOSIVES,
		SPEC_THIEF_DAREDEVIL,
		SPEC_RANGER_MARKSMANSHIP,
		SPEC_REV_RETRIBUTION,
		SPEC_MES_DOMINAION,
		SPEC_WAR_TACTICS,
		SPEC_REV_SALVATION,
		SPEC_GUARD_VALOR,
		SPEC_REV_CORRUPTION,
		SPEC_REV_DEVASTATION,
		SPEC_GUARD_RADIANCE,
		SPEC_ELE_WATER,
		SPEC_WAR_BERSERKER,
		SPEC_NECRO_BLOOD_MAGIC,
		SPEC_THIEF_SHADOW_ARTS,
		SPEC_ENGI_TOOLS,
		SPEC_WAR_DEFENSE,
		SPEC_MES_INSPIRATION,
		SPEC_MES_ILLUSIONS,
		SPEC_RANGER_NATURE_MAGIC,
		SPEC_ELE_EARTH,
		SPEC_GUARD_DRAGONHUNTER,
		SPEC_THIEF_DEADLY_ARTS,
		SPEC_ENGI_ALCHEMY,
		SPEC_RANGER_SKIRMISHING,
		SPEC_ELE_FIRE,
		SPEC_RANGER_BEASTMASTERY,
		SPEC_RANGER_WILDERNESS_SURVIVAL,
		SPEC_NECRO_REAPER,
		SPEC_THIEF_CRITICAL_STRIKES,
		SPEC_WAR_ARMS,
		SPEC_ELE_ARCANE,
		SPEC_ENGI_FIREARMS,
		SPEC_NECRO_CURSES,
		SPEC_MES_CHRONOMANCER,
		SPEC_ELE_AIR,
		SPEC_GUARD_ZEAL,
		SPEC_ENGI_SCRAPPER,
		SPEC_THIEF_TRICKERY,
		SPEC_MES_CHAOS,
		SPEC_GUARD_VIRTUES,
		SPEC_ENGI_INVENTIONS,
		SPEC_ELE_TEMPEST,
		SPEC_GUARD_HONOR,
		SPEC_NECRO_SOUL_REAPING,
		SPEC_WAR_DISCIPLINE,
		SPEC_REV_HERALD,
		SPEC_NECRO_SPITE,
		SPEC_THIEF_ACROBATICS,
		SPEC_END
	};

	enum Trait {
		TRAIT_NONE,
		// Mes Dueling
		TRAIT_MES_PHANTASMAL_FURY = 701,
		TRAIT_MES_DESPERATE_DECOY = 705,
		TRAIT_MES_DUELISTS_DISCIPLINE = 700,
		TRAIT_MES_BLINDING_DISSIPATION = 1889,
		TRAIT_MES_EVASIVE_MIRROR = 1960,
		TRAIT_MES_FENCERS_FINESSE = 708,
		TRAIT_MES_HARMONIOUS_MANTRAS = 692,
		TRAIT_MES_MISTRUST = 1950,
		TRAIT_MES_DECEPTIVE_EVASION = 704,
		// Necro Death Magic
		TRAIT_NECRO_FLESH_OF_THE_MASTER = 820,
		TRAIT_NECRO_SHROUDED_REMOVAL = 857,
		TRAIT_NECRO_PUTRID_DEFENSE = 1922,
		TRAIT_NECRO_NECROMANTIC_CORRUPTION = 858,
		TRAIT_NECRO_REAPERS_PROTECTION = 860,
		TRAIT_NECRO_DEADLY_STRENGTH = 855,
		TRAIT_NECRO_DEATH_NOVA = 842,
		TRAIT_NECRO_CORRUPTERS_FAVOR = 1940,
		TRAIT_NECRO_UNHOLY_SANCTUARY = 1694,
		// Rev Invo
		TRAIT_REV_Cruel_Repercussion = 1732,
		TRAIT_REV_Cleansing_Channel = 1761,
		TRAIT_REV_Fierce_Infusion = 1784,
		TRAIT_REV_Equilibrium = 1774,
		TRAIT_REV_Invigorating_Flow = 1760,
		TRAIT_REV_Increased_Response = 1781,
		TRAIT_REV_Roiling_Mists = 1749,
		TRAIT_REV_Charged_Mists = 1791,
		TRAIT_REV_Shrouding_Mists = 1719,
		//_War_Strength
		TRAIT_WAR_Death_from_Above = 1447,
		TRAIT_WAR_Restorative_Strength = 1451,
		TRAIT_WAR_Peak_Performance = 1444,
		TRAIT_WAR_Body_Blow = 2000,
		TRAIT_WAR_Forceful_Greatsword = 1338,
		TRAIT_WAR_Great_Fortitude = 1449,
		TRAIT_WAR_Berserkers_Power = 1437,
		TRAIT_WAR_Distracting_Strikes = 1454,
		TRAIT_WAR_Axe_Mastery = 1440,
		//_Ranger_Druid
		TRAIT_RANGER_Druidic_Clarity = 1868,
		TRAIT_RANGER_Cultivated_Synergy = 2016,
		TRAIT_RANGER_Primal_Echoes = 1935,
		TRAIT_RANGER_Celestial_Shadow = 2053,
		TRAIT_RANGER_Verdant_Etching = 2001,
		TRAIT_RANGER_Natural_Stride = 2051,
		TRAIT_RANGER_Grace_of_the_Land = 2057,
		TRAIT_RANGER_Lingering_Light = 2058,
		TRAIT_RANGER_Ancient_Seeds = 2055,
		//_Engi_Explosives
		TRAIT_ENGI_Grenadier = 514,
		TRAIT_ENGI_Explosive_Descent = 525,
		TRAIT_ENGI_Glass_Cannon = 1882,
		TRAIT_ENGI_Aim_Assisted_Rocket = 482,
		TRAIT_ENGI_Sharped_Charge = 1892,
		TRAIT_ENGI_Short_Fuse = 1944,
		TRAIT_ENGI_Siege_Rounds = 1541,
		TRAIT_ENGI_Sharpnel = 505,
		TRAIT_ENGI_Thermobaric_Detonation = 1947,
		//_Thief_Daredevil
		TRAIT_THIEF_Havoc_Mastery = 1933,
		TRAIT_THIEF_Weakening_Strikes = 2023,
		TRAIT_THIEF_Brawlers_Tenacity = 1949,
		TRAIT_THIEF_Staff_Master = 1884,
		TRAIT_THIEF_Escapists_Absolution = 1893,
		TRAIT_THIEF_Impacting_Disruption = 1975,
		TRAIT_THIEF_Lotus_Training = 1833,
		TRAIT_THIEF_Unhindered_Combatant = 1964,
		TRAIT_THIEF_Bounding_Dodger = 2047,
		//_Ranger_Marksmanship
		TRAIT_RANGER_Enlargement = 1021,
		TRAIT_RANGER_Perdators_Instinct = 1014,
		TRAIT_RANGER_Clarion_Bond = 986,
		TRAIT_RANGER_Brutish_Seals = 1001,
		TRAIT_RANGER_Steady_Focus = 1000,
		TRAIT_RANGER_Moment_of_Clarity = 1070,
		TRAIT_RANGER_Predators_Onslaught = 996,
		TRAIT_RANGER_Remorseless = 1015,
		TRAIT_RANGER_Lead_the_Wind = 1698,
		//_Rev_Retri
		TRAIT_REV_Planar_Protection = 1811,
		TRAIT_REV_Close_Quarters = 1728,
		TRAIT_REV_Improved_Aggression = 1810,
		TRAIT_REV_Eye_for_an_Eye = 1766,
		TRAIT_REV_Retaliatory_Evasion = 1782,
		TRAIT_REV_Dwarven_Battle_Training = 1740,
		TRAIT_REV_Empowering_Vengeance = 1779,
		TRAIT_REV_Versed_in_Stone = 1770,
		TRAIT_REV_Steadfast_Rejuvenation = 1790,
		//_Mes_Domination
		TRAIT_MES_Confounding_Suggestions = 686,
		TRAIT_MES_Empowered_Illusions = 682,
		TRAIT_MES_Rending_Shatter = 687,
		TRAIT_MES_Shattered_Concentration = 693,
		TRAIT_MES_Blurred_Inscriptions = 713,
		TRAIT_MES_Furious_Interruption = 712,
		TRAIT_MES_Imagined_Burden = 681,
		TRAIT_MES_Mental_Anguish = 680,
		TRAIT_MES_Power_Block = 1688,
		//_War_Tactics
		TRAIT_WAR_Leg_Specialist = 1469,
		TRAIT_WAR_Quick_Breating = 1474,
		TRAIT_WAR_Empowered = 1471,
		TRAIT_WAR_Shrug_it_Off = 1486,
		TRAIT_WAR_Burning_Arrows = 1479,
		TRAIT_WAR_Empower_Allies = 1482,
		TRAIT_WAR_Powerful_Synergy = 1667,
		TRAIT_WAR_Vigorous_Shouts = 1470,
		TRAIT_WAR_Phalanx_Strength = 1711,
		//_Rev_Salvation
		TRAIT_REV_Nourishing_Roots = 1823,
		TRAIT_REV_Blinding_Truths = 1824,
		TRAIT_REV_Tranquil_Balance = 1822,
		TRAIT_REV_Tranquil_Benediction = 1819,
		TRAIT_REV_Eluding_Nullification = 1817,
		TRAIT_REV_Invoking_Harmony = 1818,
		TRAIT_REV_Selfless_Amplification = 1815,
		TRAIT_REV_Natural_Abundance = 1825,
		TRAIT_REV_Momentary_Pacification = 1820,
		//_Guard_Valor
		TRAIT_GUARD_Strength_of_the_Fallen = 588,
		TRAIT_GUARD_Smiters_Boon = 581,
		TRAIT_GUARD_Focus_Mastery = 633,
		TRAIT_GUARD_Stalwart_Defender = 580,
		TRAIT_GUARD_Strength_in_Numbers = 584,
		TRAIT_GUARD_Communal_Defenses = 1684,
		TRAIT_GUARD_Altruistic_Healing = 585,
		TRAIT_GUARD_Monks_Focus = 586,
		TRAIT_GUARD_Retributive_Armor = 589,
		//_Rev_Courruption
		TRAIT_REV_Replenishing_Despair = 1793,
		TRAIT_REV_Demonic_Defiance = 1789,
		TRAIT_REV_Venom_Enhancement = 1741,
		TRAIT_REV_Bolstered_Anguish = 01727,
		TRAIT_REV_Frigid_Precision = 1726,
		TRAIT_REV_Spontaneous_Destruction = 1714,
		TRAIT_REV_Diabolic_Inferno = 1795,
		TRAIT_REV_Manaical_Persistence = 1720,
		TRAIT_REV_Pulsating_Pestilence = 1721,
		//_Rev_Devastation
		TRAIT_REV_Ferocious_Strikes = 1776,
		TRAIT_REV_Vicious_Lacerations = 1767,
		TRAIT_REV_Malicious_Reprisal = 1755,
		TRAIT_REV_Jade_Echo = 1786,
		TRAIT_REV_Nefarious_Momentum = 1765,
		TRAIT_REV_Assassins_Presence = 1802,
		TRAIT_REV_Swift_Termination = 1715,
		TRAIT_REV_Dismantle_Fortifications = 1800,
		TRAIT_REV_Assassins_Annhilation = 1754,
		//_Guard_Radiance
		TRAIT_GUARD_Inner_Fire = 577,
		TRAIT_GUARD_Right_Hand_Strength = 566,
		TRAIT_GUARD_Healers_Retribution = 574,
		TRAIT_GUARD_Wrath_of_Justice = 578,
		TRAIT_GUARD_Radiant_Fire = 567,
		TRAIT_GUARD_Retribution = 565,
		TRAIT_GUARD_Amplified_Wrath = 1686,
		TRAIT_GUARD_Perfect_Inscriptions = 579,
		TRAIT_GUARD_Radiant_Retaliation = 1683,
		//_Ele_Water
		TRAIT_ELE_Soothing_Ice = 348,
		TRAIT_ELE_Piercing_Shards = 363,
		TRAIT_ELE_Stop_Drop_and_Roll = 360,
		TRAIT_ELE_Soothing_Disruption = 364,
		TRAIT_ELE_Cleansing_Wave = 358,
		TRAIT_ELE_Aquamancers_Training = 349,
		TRAIT_ELE_Cleansing_Water = 362,
		TRAIT_ELE_Powerful_Aura = 361,
		TRAIT_ELE_Soothing_Power = 2028,
		//_War_Berserker
		TRAIT_WAR_Smash_Brawler = 2049,
		TRAIT_WAR_Last_Blaze = 2039,
		TRAIT_WAR_Savage_Instinct = 1977,
		TRAIT_WAR_Blood_Reaction = 2011,
		TRAIT_WAR_Heal_the_Soul = 2042,
		TRAIT_WAR_Dead_or_Alive = 2002,
		TRAIT_WAR_Bloody_Roar = 1928,
		TRAIT_WAR_King_of_Fires = 2038,
		TRAIT_WAR_Eternal_Champion = 2043,
		//_Necro_Blood_Magic
		TRAIT_NEC_Ritual_of_Life = 780,
		TRAIT_NEC_Quickening_Thirst = 788,
		TRAIT_NEC_Blood_Bond = 1876,
		TRAIT_NEC_Life_from_Death = 789,
		TRAIT_NEC_Banshees_Wail = 799,
		TRAIT_NEC_Vampiric_Presence = 1844,
		TRAIT_NEC_Vampiric_Rituals = 782,
		TRAIT_NEC_Unholy_Martyr = 1692,
		TRAIT_NEC_Transfusion = 778,
		//_Thief_Shadow_Arts
		TRAIT_THIEF_Last_Refuge = 1160,
		TRAIT_THIEF_Concealed_Defeat = 1293,
		TRAIT_THIEF_Shadows_Embrace = 1284,
		TRAIT_THIEF_Shadow_Protector = 1297,
		TRAIT_THIEF_Hidden_Thief = 1130,
		TRAIT_THIEF_Leeching_Venoms = 1300,
		TRAIT_THIEF_Cloaked_in_Shadows = 1134,
		TRAIT_THIEF_Shadows_Rejuvenation = 1135,
		TRAIT_THIEF_Rending_Shade = 1162,
		//_Engi_Tools
		TRAIT_ENGI_Static_Discharge = 532,
		TRAIT_ENGI_Reactive_Lenses = 1997,
		TRAIT_ENGI_Power_Wrench = 531,
		TRAIT_ENGI_Streamlined_Kits = 512,
		TRAIT_ENGI_Lock_On = 1946,
		TRAIT_ENGI_Takedown_Round = 1832,
		TRAIT_ENGI_Kinetic_Battery = 1856,
		TRAIT_ENGI_Adrenal_Implant = 523,
		TRAIT_ENGI_Gadgeteer = 1679,
		//_War_Defense
		TRAIT_WAR_Shield_Master = 1376,
		TRAIT_WAR_Dogged_March = 1488,
		TRAIT_WAR_Cull_the_Weak = 1372,
		TRAIT_WAR_Defy_Pain = 1368,
		TRAIT_WAR_Armored_Attack = 1379,
		TRAIT_WAR_Sundering_Mace = 1367,
		TRAIT_WAR_Last_Stand = 1375,
		TRAIT_WAR_Cleansing_Ire = 1649,
		TRAIT_WAR_Rousing_Resilience = 1708,
		//_Mes_Inspiration
		TRAIT_MES_Medics_Feedback = 756,
		TRAIT_MES_Restorative_Mantras = 738,
		TRAIT_MES_Persisting_Images = 744,
		TRAIT_MES_Wardens_Feedback = 751,
		TRAIT_MES_Restorative_Illusions = 740,
		TRAIT_MES_Protected_Phantasms = 1980,
		TRAIT_MES_Mental_Defense = 2005,
		TRAIT_MES_Illusionary_Inspiration = 1866,
		TRAIT_MES_Temporal_Enchanter = 752,
		//_Mes_Illusions
		TRAIT_MES_Compunding_Power = 721,
		TRAIT_MES_Persistence_of_Memory = 1869,
		TRAIT_MES_The_Pledge = 691,
		TRAIT_MES_Shattered_Strength = 722,
		TRAIT_MES_Phantasmal_Haste = 729,
		TRAIT_MES_Maim_the_Disillusioned = 1690,
		TRAIT_MES_Ineptitude = 733,
		TRAIT_MES_Master_of_Fragmentation = 2035,
		TRAIT_MES_Malicious_Sorcery = 753,
		//_Ranger_Nature_Magic
		TRAIT_RANGER_Bountiful_Hunter = 1062,
		TRAIT_RANGER_Instinctive_Reaction = 978,
		TRAIT_RANGER_Allies_Aid = 1060,
		TRAIT_RANGER_Evasive_Purity = 1054,
		TRAIT_RANGER_Vigorous_Training = 965,
		TRAIT_RANGER_Windborne_Notes = 964,
		TRAIT_RANGER_Natures_Vengeance = 1038,
		TRAIT_RANGER_Protective_Ward = 1988,
		TRAIT_RANGER_Invigorating_Bond = 1697,
		//_Ele_Earth
		TRAIT_ELE_Earths_Embrace = 282,
		TRAIT_ELE_Serrated_Stones = 1507,
		TRAIT_ELE_Elemental_Shielding = 289,
		TRAIT_ELE_Strength_of_Stone = 275,
		TRAIT_ELE_Rock_Solid = 281,
		TRAIT_ELE_Geomancers_Training = 277,
		TRAIT_ELE_Diamond_Skin = 1508,
		TRAIT_ELE_Written_in_Stone = 287,
		TRAIT_ELE_Stone_Heart = 1674,
		//_Guard_DH
		TRAIT_GUARD_Piercing_Light = 1898,
		TRAIT_GUARD_Dulled_Senses = 1983,
		TRAIT_GUARD_Soaring_Devastation = 1911,
		TRAIT_GUARD_Hunters_Determination = 2037,
		TRAIT_GUARD_Zealots_Aggression = 1835,
		TRAIT_GUARD_Bulwark = 1943,
		TRAIT_GUARD_Hunters_Fortification = 1908,
		TRAIT_GUARD_Heavy_Light = 1963,
		TRAIT_GUARD_Big_Game_Hunter = 1955,
		//_Thief_Deadly_Arts
		TRAIT_THIEF_Dagger_Training = 1245,
		TRAIT_THIEF_Mug = 1276,
		TRAIT_THIEF_Trappers_Respite = 1164,
		TRAIT_THIEF_Deadly_Trapper = 1169,
		TRAIT_THIEF_Panic_Strikes = 1292,
		TRAIT_THIEF_Revealed_Training = 1704,
		TRAIT_THIEF_Potent_Poison = 1291,
		TRAIT_THIEF_Improvisation = 1167,
		TRAIT_THIEF_Executioner = 1269,
		//_Engi_Alchemy
		TRAIT_ENGI_Invigorating_Speed = 396,
		TRAIT_ENGI_Protection_Injection = 509,
		TRAIT_ENGI_Health_Insurance = 521,
		TRAIT_ENGI_Inversion_Enzyme = 520,
		TRAIT_ENGI_Self_Regulating_Defenses = 469,
		TRAIT_ENGI_Backpack_Regenrator = 470,
		TRAIT_ENGI_HGH = 473,
		TRAIT_ENGI_Stimulant_Supplier = 1871,
		TRAIT_ENGI_Iron_Blooded = 1854,
		//_Ranger_Skirmish
		TRAIT_RANGER_Sharpened_Edges = 1069,
		TRAIT_RANGER_Primal_Reflexes = 1067,
		TRAIT_RANGER_Trappers_Expertise = 1075,
		TRAIT_RANGER_Spotter = 1016,
		TRAIT_RANGER_Striders_Defense = 1700,
		TRAIT_RANGER_Hidden_Barbs = 1846,
		TRAIT_RANGER_Quick_Draw = 1064,
		TRAIT_RANGER_Light_on_your_Feet = 1912,
		TRAIT_RANGER_Most_Dangerous_Game = 1888,
		//_Ele_Fire
		TRAIT_ELE_Burning_Precision = 296,
		TRAIT_ELE_Conjurer = 328,
		TRAIT_ELE_Burning_Fire = 335,
		TRAIT_ELE_Pyromancers_Training = 325,
		TRAIT_ELE_One_with_Fire = 340,
		TRAIT_ELE_Power_Overwhelming = 334,
		TRAIT_ELE_Persisting_Flames = 1510,
		TRAIT_ELE_Pyromancers_Puissance = 294,
		TRAIT_ELE_Blinding_Ashes = 1675,
		//_Ranger_Beastmastery
		TRAIT_RANGER_Go_for_the_Eyes = 1861,
		TRAIT_RANGER_Companions_Might = 1072,
		TRAIT_RANGER_Resounding_Timbre = 1606,
		TRAIT_RANGER_Wilting_Strike = 975,
		TRAIT_RANGER_Two_Handed_Training = 1047,
		TRAIT_RANGER_Natural_Healing = 970,
		TRAIT_RANGER_Beastly_Warden = 1945,
		TRAIT_RANGER_Zephyrs_Speed = 968,
		TRAIT_RANGER_Hones_Axes = 1066,
		//_Ranger_Wildreness_Survival
		TRAIT_RANGER_Soften_the_Fall = 1098,
		TRAIT_RANGER_Oakheart_Salve = 1086,
		TRAIT_RANGER_Expertise_Training = 1099,
		TRAIT_RANGER_Ambidexterity = 1101,
		TRAIT_RANGER_Refined_Toxins = 2032,
		TRAIT_RANGER_Shared_Anguish = 1100,
		TRAIT_RANGER_Empathic_Bond = 1094,
		TRAIT_RANGER_Wilderness_Knowledge = 1699,
		TRAIT_RANGER_Poison_Master = 1701,
		//_Necro_Reaper
		TRAIT_NEC_Augury_of_Death = 1974,
		TRAIT_NEC_Chilling_Nova = 2020,
		TRAIT_NEC_Relentless_Pursuit = 2026,
		TRAIT_NEC_Soul_Eater = 1969,
		TRAIT_NEC_Chilling_Victory = 2008,
		TRAIT_NEC_Decimate_Defenses = 2031,
		TRAIT_NEC_Blighters_Boon = 1932,
		TRAIT_NEC_Deathly_Chill = 1919,
		TRAIT_NEC_Reapers_Onslaught = 2021,
		//_Thief_Crit_Strikes
		TRAIT_THIEF_Side_Strike = 1209,
		TRAIT_THIEF_Signets_of_Power = 1267,
		TRAIT_THIEF_Flawless_Strike = 1268,
		TRAIT_THIEF_Sundering_Strikes = 1170,
		TRAIT_THIEF_Practiced_Tolerance = 1272,
		TRAIT_THIEF_Ankle_Shots = 1299,
		TRAIT_THIEF_No_Quarter = 1904,
		TRAIT_THIEF_Hidden_Killer = 1215,
		TRAIT_THIEF_Invigorating_Precision = 1702,
		//_War_Arms
		TRAIT_WAR_Berserks_Fury = 1455,
		TRAIT_WAR_Signet_Mastery = 1344,
		TRAIT_WAR_Opportunist = 1334,
		TRAIT_WAR_Unsuspecting_Foe = 1315,
		TRAIT_WAR_Deep_Strikes = 1316,
		TRAIT_WAR_Blademaster = 1333,
		TRAIT_WAR_Burst_Precision = 1336,
		TRAIT_WAR_Furious = 1346,
		TRAIT_WAR_Dual_Wielding = 1707,
		//_Ele_Arcane
		TRAIT_ELE_Arcane_Precision = 253,
		TRAIT_ELE_Renewing_Stamina = 266,
		TRAIT_ELE_Arcane_Abatement = 1487,
		TRAIT_ELE_Arcane_Resurrection = 265,
		TRAIT_ELE_Elemental_Contingency = 1673,
		TRAIT_ELE_Final_Shielding = 257,
		TRAIT_ELE_Evasive_Arcana = 238,
		TRAIT_ELE_Elemental_Surge = 263,
		TRAIT_ELE_Bountiful_Power = 1511,
		//_Engi_Firearms
		TRAIT_ENGI_Chemical_Rounds = 1878,
		TRAIT_ENGI_Heavy_Armor_Exploit = 1930,
		TRAIT_ENGI_High_Caliber = 1914,
		TRAIT_ENGI_Pinpoint_Distribution = 1984,
		TRAIT_ENGI_Skilled_Marksman = 2006,
		TRAIT_ENGI_No_Scope = 1923,
		TRAIT_ENGI_Juggernaut = 510,
		TRAIT_ENGI_Modified_Ammunition = 526,
		TRAIT_ENGI_Incendiary_Powder = 433,
		//_Necro_Curses
		TRAIT_NEC_Terrifying_Descent = 1883,
		TRAIT_NEC_Plague_Sending = 2013,
		TRAIT_NEC_Chilling_Darkness = 815,
		TRAIT_NEC_Master_of_Corruption = 816,
		TRAIT_NEC_Path_of_Corruption = 1693,
		TRAIT_NEC_Terror = 812,
		TRAIT_NEC_Weakening_Shroud = 813,
		TRAIT_NEC_Parasitic_Contagion = 1696,
		TRAIT_NEC_Lingering_Curse = 801,
		//_Mes_Chrono
		TRAIT_MES_Delayed_Reactions = 1838,
		TRAIT_MES_Time_Catches_Up = 1995,
		TRAIT_MES_Alls_Well_That_Ends_Well = 1987,
		TRAIT_MES_Danger_Time = 2009,
		TRAIT_MES_Illusionairy_Reversion = 1913,
		TRAIT_MES_Improved_Alacrity = 1978,
		TRAIT_MES_Lost_Time = 1942,
		TRAIT_MES_Seize_the_Moment = 2022,
		TRAIT_MES_Chronophantasma = 1890,
		//_Ele_Air
		TRAIT_ELE_Zephyrs_Boon = 227,
		TRAIT_ELE_One_with_Air = 224,
		TRAIT_ELE_Ferocious_Winds = 232,
		TRAIT_ELE_Inscription = 229,
		TRAIT_ELE_Aeromancers_Training = 214,
		TRAIT_ELE_Tempest_Defense = 1502,
		TRAIT_ELE_Bolt_to_the_Heart = 226,
		TRAIT_ELE_Fresh_Air = 1503,
		TRAIT_ELE_Lightning_Rod = 1672,
		//_Guard_Zeal
		TRAIT_GUARD_Wrathful_Spirit = 563,
		TRAIT_GUARD_Fiery_Wrath = 634,
		TRAIT_GUARD_Zealous_Scepter = 1925,
		TRAIT_GUARD_Blinding_Jeopardy = 628,
		TRAIT_GUARD_Zealous_Blade = 653,
		TRAIT_GUARD_Kindles_Zeal = 1556,
		TRAIT_GUARD_Expeditious_Spirit = 635,
		TRAIT_GUARD_Shattered_Aegis = 637,
		TRAIT_GUARD_Symbolic_Avenger = 2017,
		//_Engi_Scrapper
		TRAIT_ENGI_Shocking_Speed = 1917,
		TRAIT_ENGI_Perfectly_Weighted = 1971,
		TRAIT_ENGI_Recovery_Matrix = 1867,
		TRAIT_ENGI_Rapid_Regenration = 1954,
		TRAIT_ENGI_Expert_Examination = 1999,
		TRAIT_ENGI_Mass_Momentum = 1860,
		TRAIT_ENGI_Adaptive_Armor = 1981,
		TRAIT_ENGI_Final_Salvo = 2052,
		TRAIT_ENGI_Applied_Force = 1849,
		//_Thief_Trickery
		TRAIT_THIEF_Uncatchable = 1159,
		TRAIT_THIEF_Flanking_Strikes = 1252,
		TRAIT_THIEF_Thrill_of_the_Crime = 1163,
		TRAIT_THIEF_Bountiful_Theft = 1277,
		TRAIT_THIEF_Trickster = 1286,
		TRAIT_THIEF_Pressure_Striking = 1190,
		TRAIT_THIEF_Quick_Pockets = 1187,
		TRAIT_THIEF_Sleight_of_Hand = 1158,
		TRAIT_THIEF_Bewildering_Ambush = 1706,
		//_Mes_Chaos
		TRAIT_MES_Descent_into_Madness = 670,
		TRAIT_MES_Illusionary_Defenses = 675,
		TRAIT_MES_Master_of_Manipulation = 677,
		TRAIT_MES_Mirror_of_Anguish = 673,
		TRAIT_MES_Chaotic_Transference = 668,
		TRAIT_MES_Chaotic_Dampening = 669,
		TRAIT_MES_Chaotic_Interruption = 671,
		TRAIT_MES_Prismatic_Understanding = 674,
		TRAIT_MES_Bountiful_Disillusionment = 1687,
		//_Guard_Virtues
		TRAIT_GUARD_Unscathed_Contender = 624,
		TRAIT_GUARD_Retaliatory_Subconscious = 625,
		TRAIT_GUARD_Master_of_Consecrations = 617,
		TRAIT_GUARD_Virtuous_Solace = 603,
		TRAIT_GUARD_Absolute_Resolution = 610,
		TRAIT_GUARD_Glacial_Heart = 587,
		TRAIT_GUARD_Permeating_Wrath = 622,
		TRAIT_GUARD_Battle_Presence = 554,
		TRAIT_GUARD_Indomitable_Courage = 612,
		//_Engi_Inventions
		TRAIT_ENGI_Over_Shield = 394,
		TRAIT_ENGI_Automated_Medical_Response = 1901,
		TRAIT_ENGI_Autodefense_Bomb_Dispenser = 507,
		TRAIT_ENGI_Experimental_Turrets = 1678,
		TRAIT_ENGI_Soothing_Detonation = 1834,
		TRAIT_ENGI_Mecha_Legs = 445,
		TRAIT_ENGI_Advanced_Turrets = 472,
		TRAIT_ENGI_Bunker_Down = 1680,
		TRAIT_ENGI_Medical_Disersion_Field = 1916,
		//_Ele_Tempest
		TRAIT_ELE_Gale_Song = 1952,
		TRAIT_ELE_Latent_Stamina = 1962,
		TRAIT_ELE_Unstable_Conduit = 1886,
		TRAIT_ELE_Tempestuous_Aria = 1891,
		TRAIT_ELE_Invigorating_Torrents = 1902,
		TRAIT_ELE_Harmonious_Conduit = 2015,
		TRAIT_ELE_Imbued_Melodies = 1839,
		TRAIT_ELE_Lucid_Singularity = 2033,
		TRAIT_ELE_Elemental_Bastion = 1986,
		//_Guard_Honor
		TRAIT_GUARD_Invigorated_Bulwark = 1899,
		TRAIT_GUARD_Protective_Reviver = 559,
		TRAIT_GUARD_Protectors_Impact = 654,
		TRAIT_GUARD_Honorable_Staff = 557,
		TRAIT_GUARD_Pure_of_Heart = 549,
		TRAIT_GUARD_Empowering_Might = 562,
		TRAIT_GUARD_Pure_of_Voice = 553,
		TRAIT_GUARD_Writ_of_Persistence = 558,
		TRAIT_GUARD_Force_of_Will = 1682,
		//_Necro_Soul_Reaping
		TRAIT_NEC_Unyielding_Blast = 875,
		TRAIT_NEC_Soul_Marks = 898,
		TRAIT_NEC_Speed_of_Shadows = 888,
		TRAIT_NEC_Spectral_Mastery = 894,
		TRAIT_NEC_Vital_Persistence = 861,
		TRAIT_NEC_Fear_of_Death = 892,
		TRAIT_NEC_Foot_in_the_Grave = 889,
		TRAIT_NEC_Death_Perception = 893,
		TRAIT_NEC_Dhummfire = 905,
		//_War_Discipline
		TRAIT_WAR_Crack_Shot = 1329,
		TRAIT_WAR_Warriors_Sprint = 1413,
		TRAIT_WAR_Vengeful_Return = 1381,
		TRAIT_WAR_Inspiring_Battle_Standard = 1484,
		TRAIT_WAR_Destruction_of_the_Empowered = 1489,
		TRAIT_WAR_Brawlers_Recovery = 1709,
		TRAIT_WAR_Merciless_Hammer = 1369,
		TRAIT_WAR_Heightened_Focus = 1317,
		TRAIT_WAR_Burst_Mastery = 1657,
		//_Rev_Herald
		TRAIT_REV_Swift_Gale = 1813,
		TRAIT_REV_Radiant_Revival = 1806,
		TRAIT_REV_Hardening_Persistence = 1716,
		TRAIT_REV_Bolster_Fortifications = 1738,
		TRAIT_REV_Shared_Empowerment = 1743,
		TRAIT_REV_Harmonize_Continuity = 1730,
		TRAIT_REV_Elders_Force = 1746,
		TRAIT_REV_Soothing_Bastion = 1772,
		TRAIT_REV_Enhanced_Bulwark = 1803,
		//_Necro_Spite
		TRAIT_NEC_Spiteful_Talisman = 914,
		TRAIT_NEC_Spiteful_Renewal = 916,
		TRAIT_NEC_Bitter_Chill = 1863,
		TRAIT_NEC_Chill_of_Death = 899,
		TRAIT_NEC_Rending_Shroud = 829,
		TRAIT_NEC_Unholy_Fervor = 909,
		TRAIT_NEC_Signets_of_Suffering = 919,
		TRAIT_NEC_Close_to_Death = 853,
		TRAIT_NEC_Spitful_Spirit = 903,
		//_Thief_Acro
		TRAIT_THIEF_Instant_Reflexes = 1112,
		TRAIT_THIEF_Vigorous_Recovery = 1289,
		TRAIT_THIEF_Pain_Response = 1237,
		TRAIT_THIEF_Guarded_Initiation = 1241,
		TRAIT_THIEF_Swindlers_Equilibrium = 1192,
		TRAIT_THIEF_Hard_to_Catch = 1290,
		TRAIT_THIEF_Assassins_Reward = 1238,
		TRAIT_THIEF_Upper_Hand = 1295,
		TRAIT_THIEF_Dont_Stop = 1703,
		// End
		TRAIT_END = 100000,
	};

	enum CharacterGender {
		CHAR_GENDER_MALE,
		CHAR_GENDER_FEMALE,
		CHAR_GENDER_NONE
	};

	enum EquipmentSlot {
		EQUIP_SLOT_NONE = -1,
		EQUIP_SLOT_AQUATIC_HELM,
		EQUIP_SLOT_BACK,
		EQUIP_SLOT_CHEST,
		EQUIP_SLOT_BOOTS,
		EQUIP_SLOT_GLOVES,
		EQUIP_SLOT_HELM,
		EQUIP_SLOT_PANTS,
		EQUIP_SLOT_SHOULDERS,
		EQUIP_SLOT_TOWN_CHEST = 14,
		EQUIP_SLOT_TOWN_BOOTS,
		EQUIP_SLOT_TOWN_GLOVES,
		EQUIP_SLOT_TOWN_HELM,
		EQUIP_SLOT_TOWN_PANTS,
		EQUIP_SLOT_ACCESSORY1,
		EQUIP_SLOT_ACCESSORY2,
		EQUIP_SLOT_RING1,
		EQUIP_SLOT_RING2,
		EQUIP_SLOT_AMULET,
		EQUIP_SLOT_AQUATIC_WEAP1,
		EQUIP_SLOT_AQUATIC_WEAP2,
		EQUIP_SLOT_MAINHAND_WEAP1 = 29,
		EQUIP_SLOT_OFFHAND_WEAP1,
		EQUIP_SLOT_MAINHAND_WEAP2,
		EQUIP_SLOT_OFFHAND_WEAP2,
		EQUIP_SLOT_TOY,
		EQUIP_SLOT_FORAGING_TOOL,
		EQUIP_SLOT_LOGGING_TOOL,
		EQUIP_SLOT_MINING_TOOL,
		EQUIP_SLOT_END = 60
	};

	enum ItemRarity {
		RARITY_NONE = -1,
		RARITY_JUNK,
		RARITY_COMMON,
		RARITY_FINE,
		RARITY_MASTERWORK,
		RARITY_RARE,
		RARITY_EXOTIC,
		RARITY_ASCENDED,
		RARITY_LEGENDARY,
		RARITY_END
	};

	enum BuffStackType {
		BUFF_STACK_TYPE_CUMULATIVE = 1,
		BUFF_STACK_TYPE_PROGRESSIVE,
		BUFF_STACK_TYPE_END
	};

	enum EffectType {
		EFFECT_NONE,
		EFFECT_PROTECTION = 717,
		EFFECT_REGENERATION = 718,
		EFFECT_SWIFTNESS = 719,
		EFFECT_FURY = 725,
		EFFECT_VIGOR = 726,
		EFFECT_SIGNET_OF_RESTORATION = 739,
		EFFECT_MIGHT = 740,
		EFFECT_AEGIS = 743,
		EFFECT_RETALIATION = 873,
		EFFECT_STABILITY = 1122,
		EFFECT_BLEEDING = 736,
		EFFECT_BLIND = 720,
		EFFECT_BURNING = 737,
		EFFECT_CHILLED = 722,
		EFFECT_CONFUSION = 861,
		EFFECT_CRIPPLED = 721,
		EFFECT_FEAR = 791,
		EFFECT_IMMOBILIZED = 727,
		EFFECT_POISON = 723,
		EFFECT_VULNERABILITY = 738,
		EFFECT_WEAKNESS = 742,
		EFFECT_MES_SIGNET_DOM = 10231,
		EFFECT_BLUR = 10335,
		EFFECT_DETERMINED = 11641,
		EFFECT_DISTORTION = 10371,
		EFFECT_ELIXIRS = 5863,
		EFFECT_FRENZY = 14456,
		EFFECT_HASTE = 13067,
		EFFECT_MISTFORMBUFF1 = 3686,
		EFFECT_MISTFORMBUFF2 = 5543,
		EFFECT_PETRIFIED = 15090,
		EFFECT_QUICKENINGZEPHYR = 12551,
		EFFECT_RENEWEDFOCUS = 9255,
		EFFECT_REVEALED = 890,
		EFFECT_STUN = 872,
		EFFECT_SVANIRICEBLOCK = 9636,
		EFFECT_QUICKNESS = 1187,
		EFFECT_INVULNERABILITY = 848,
		EFFECT_PORTAL_WEAVING = 10198,
		EFFECT_PORTAL_WEAVING2 = 34978,	// White mantle portal device / watchwork portal device
		EFFECT_STEALTH = 13017,
		EFFECT_PORTAL = 16553,
		EFFECT_TORMENT = 19426,
		EFFECT_SLOW = 26766,
		EFFECT_ALACRITY = 30328,
		EFFECT_CONJURE_FROST_CHARGES = 5729,
		EFFECT_CONJURE_FROST_ATTRIBUTES = 15790,
		EFFECT_CONJURE_FIRE_CHARGES = 5759,
		EFFECT_CONJURE_FIRE_ATTRIBUTES = 15792,
		EFFECT_CONJURE_EARTH_CHARGES = 5730,
		EFFECT_CONJURE_EARTH_ATTRIBUTES = 15788,
		EFFECT_CONJURE_FLAME_CHARGES = 5704,
		EFFECT_CONJURE_FLAME_ATTRIBUTES = 15789,
		EFFECT_ATTUNEMENT_OVERLOADING = 30608,
		EFFECT_REBOUND = 31337,
		EFFECT_STATIC_CHARGE = 31487, // From overload air
		EFFECT_RIDE_THE_LIGHTNING = 3686,
		EFFECT_BURNING_SPEED = 25503,
		EFFECT_UNSTEADY_GROUND = 34706,
		EFFECT_STATIC_FIELD = 34641,
		EFFECT_BURNING_RETREAT = 25502,
		EFFECT_ARCANE_LIGHTNING = 13423,
		EFFECT_FIRE_SHIELD = 5677,
		EFFECT_MAGNETIC_AURA = 5684,
		EFFECT_SHOCKING_AURA = 5577,
		EFFECT_FROST_AURA = 5579,
		EFFECT_SUPERSPEED = 5974,
		EFFECT_OBSIDIAN_FLESH = 5667,
		EFFECT_MAGNETIC_WAVE = 15794, // Scepter Earth 4
		EFFECT_TORNADO = 5583,
		EFFECT_SOOTHING_MIST = 5587,
		EFFECT_UNDERWATER_AIR_POCKET = 5654,
		EFFECT_UNDERWATER_ICE_WALL = 5613,
		EFFECT_UNDERWATER_ICE_GLOBE = 5612,
		EFFECT_TRAIT_ELEMENTALIST_DIAMOND_SKIN = 22560,
		EFFECT_TRAIT_ELEMENTALIST_EARTHS_EMBRACE = 13369,
		EFFECT_TRAIT_ELEMENTALIST_SERRATED_STONES = 13424,
		EFFECT_TRAIT_ELEMENTALIST_ELEMENTAL_SHIELDING = 13415,
		EFFECT_TRAIT_ELEMENTALIST_STRENGTH_OF_STONE = 13371,
		EFFECT_TRAIT_ELEMENTALIST_ROCK_SOLID = 19522,
		EFFECT_GLYPH_REVIVAL_OF_FIRE = 5764,
		EFFECT_GLYPH_REVIVAL_OF_AIR = 5765,
		EFFECT_GLYPH_LESSER_AIR_ELEMENTAL = 25481,
		EFFECT_GLYPH_AIR_ELEMENTAL = 25496,
		EFFECT_GLYPH_LESSER_FIRE_ELEMENTAL = 25475,
		EFFECT_GLYPH_FIRE_ELEMENTAL = 25475,
		EFFECT_GLYPH_LESSER_ICE_ELEMENTAL = 25483,
		EFFECT_GLYPH_ICE_ELEMENTAL = 25493,
		EFFECT_GLYPH_LESSER_EARTH_ELEMENTAL = 25484,
		EFFECT_GLYPH_EARTH_ELEMENTAL = 25477,
		EFFECT_GLYPH_ARCANE_POWER_STACK = 5582,
		EFFECT_GLYPH_ARCANE_POWER_EFFECT = 20449,
		EFFECT_GLYPH_ELEMENTAL_POWER_FIRE = 5739,
		EFFECT_GLYPH_ELEMENTAL_POWER_AIR = 5740,
		EFFECT_GLYPH_ELEMENTAL_POWER_WATER = 5741,
		EFFECT_GLYPH_ELEMENTAL_POWER_EARTH = 5742,
		EFFECT_ATTUNEMENT_AIR = 5575,
		EFFECT_ATTUNEMENT_FIRE = 5585,
		EFFECT_ATTUNEMENT_WATER = 5568,
		EFFECT_ATTUNEMENT_EARTH = 5580,
		EFFECT_ARCANE_SHIELD_STACK = 5640,
		EFFECT_ARCANE_SHIELD_EFFECT = 20450,
		EFFECT_ROCK_BARRIER_EFFECT = 34633,
		EFFECT_ROCK_BARRIER_SHARD1 = 750,
		EFFECT_ROCK_BARRIER_SHARD2 = 751,
		EFFECT_ROCK_BARRIER_SHARD3 = 752,
		EFFECT_ROCK_BARRIER_SHARD4 = 753,
		EFFECT_ROCK_BARRIER_SHARD5 = 754,
		EFFECT_VAMPIRIC_AURA = 30285,
		EFFECT_SIGNET_OF_THE_LOCUST = 10614,
		EFFECT_SIGNET_OF_SPITE = 10621,
		EFFECT_SIGNET_OF_VAMPIRISM = 21761,
		EFFECT_PLAGUE_SIGNET = 10630,
		EFFECT_SIGNET_OF_UNDEATH = 10610,
		EFFECT_REAPER_SHROUD = 10668,
		EFFECT_DEATH_SHROUD = 790,
		EFFECT_LICH_FORM = 10631,
		EFFECT_BONE_MINION = 10539,
		EFFECT_BONE_FIEND = 10569,
		EFFECT_SHADOW_FIEND = 10591,
		EFFECT_BLOOD_FIEND = 10575,
		EFFECT_SPECTRAL_WALL = 34726,
		EFFECT_FLESH_GOLEM = 10648,
		EFFECT_PLAGUE_FORM = 10578,
		EFFECT_WELL_OF_POWER = 10615, // ticking condition conversion
		EFFECT_FLESH_WURM = 10599,
		EFFECT_INFUSING_TERROR = 30129, // reaper shroud 3
		EFFECT_DOWNED = 770,
		EFFECT_SPECTRAL_WALK = 15083,
		EFFECT_SPECTRAL_WALK_GAIN_LF = 10686, // gain life force when walking in the darkness
		EFFECT_SPECTRAL_ARMOR = 10582,
		EFFECT_ENDURE_PAIN = 787,
		EFFECT_HEALING_SIGNET = 786,
		EFFECT_SIGNET_OF_RAGE = 14496,
		EFFECT_RAMPAGE = 14484,
		EFFECT_SIGNET_OF_FURY = 14459,
		EFFECT_SIGNET_OF_THE_DOLYAK = 14458,
		EFFECT_SIGNET_OF_STAMINA = 14478,
		EFFECT_SIGNET_OF_MIGHT = 14444,
		EFFECT_DEFIANT_STANCE = 21816,
		EFFECT_BERSERKERS_STANCE = 14453,
		EFFECT_RESISTANCE = 26980,
		EFFECT_BALANCED_STANCE = 34778,
		EFFECT_ROUSING_RESILIANCE = 24383,
		EFFECT_BANNER_OF_DEFENSE = 14543,
		EFFECT_BANNER_OF_POWER = 14417,
		EFFECT_BANNER_OF_DISCIPLINE = 14449,
		EFFECT_BANNER_OF_TACTICS = 14450,
		EFFECT_SHIELD_STANCE = 756, // shield 5, blocking
		EFFECT_FLAMES_OF_WAR = 31708, // berserker torch 5
		EFFECT_BLOOD_RECKONING = 29466,
		EFFECT_ROCK_GUARD = 34256, // berserker rage skill
		EFFECT_ALWAYS_ANGRY = 34099, // berserker trait
		EFFECT_BERSERK = 29502,
		EFFECT_ASURA_POWER_SUIT = 12326,
		EFFECT_EXPERIENCE_BOOSTER = 31078,
		EFFECT_LAUREATE_COIN_BOOSTER = 16990,
		EFFECT_ITEM_BOOSTER = 31080,
		EFFECT_RAMS_REWARD_BOOSTER = 25627,
		EFFECT_SIEGE_MANNED = 8726,
		EFFECT_WVW_DETERMINED = 762,
		EFFECT_SIEGE_DEPLOYMENT_BLOCKED = 14712,
		EFFECT_CORRUPTION_SIGIL = 9374,
		EFFECT_GLIDING = 30955,
		EFFECT_LEADER_OF_THE_PACT_3 = 33611,
		EFFECT_EMPOWER_ALLIES = 14222,
		EFFECT_NATURALISTIC_RESONANCE = 29379,
		EFFECT_RITE_OF_THE_GREAT_DWARF = 33330,
		EFFECT_ASSASSINS_PRESENCE = 26854,
		EFFECT_SUN_SPIRIT = 12540,
		EFFECT_FROST_SPIRIT = 12544,
		EFFECT_STORM_SPIRIT = 12549,
		EFFECT_STONE_SPIRIT = 12547,
		EFFECT_SPOTTER = 14055,
		EFFECT_GRACE_OF_THE_LAND = 34062,
		EFFECT_GRACE_OF_THE_LAND_CN = 34065,	// Chinese client GOTL
		EFFECT_GLYPH_OF_EMPOWERMENT = 31803,
		EFFECT_GLYPH_OF_EMPOWERMENT_CN = 31805,
		EFFECT_STRENGTH_IN_NUMBERS = 13796,
		EFFECT_PINPOINT_DISTRIBUTION = 38333,
		EFFECT_END
	};

#ifdef __cplusplus
} // namespace GW2
#endif

#endif